### ISSUE TITLE
Registration.sh mif vs nii formats causing errors

### ISSUE THREAD

**Issue by MarshallJordan** [sotnir/NENAH-BIDS#119]
Lines 94-96 $meanb0 default is the same as output ( $datadir/dwi/meanb0_brain.nii.gz) - there is no file of the type .nii.gz produced in the preprocess script which I think it is refereing to a file with the same name but .mif.gz instead. Causing a no file/path/directory error and then various steps to not be able to complete

Later similar thing happening with anat/$mask.mif.gz which is  anat/space-t1w_mask.mif.gz in mrcalc step line 143 but in this case there is only a space-t1w_mask.nii.gz in that path

**Comment by yukaizou2015** [comment]
@finnlennartsson [Line 37](https://github.com/yukaizou2015/NENAH-BIDS/blob/ccb58acb97af0c45ed4e05e9be967badc63b67a0/dMRI/registration.sh#L37) seems to cause the issue here? The default for `$meanb0` should be `meanb0_brain.mif.gz` rather than `meanb0_brain.nii.gz`?

Seems what [lines 94-96](https://github.com/yukaizou2015/NENAH-BIDS/blob/ccb58acb97af0c45ed4e05e9be967badc63b67a0/dMRI/registration.sh#L94-L96) try to do is to create a `meanb0_brain.nii.gz` if there isn't one

In addition, a typo found for [mrcalc step line 143](https://github.com/yukaizou2015/NENAH-BIDS/blob/ccb58acb97af0c45ed4e05e9be967badc63b67a0/dMRI/registration.sh#L143), where `-mult anat/${t1w}_brain_space-dwi.mig.gz` should be `-mult anat/${t1w}_brain_space-dwi.mif.gz`

**Comment by finnlennartsson** [comment]
Yes, I think you are correct @yukaizou2015 

> @finnlennartsson [Line 37](https://github.com/yukaizou2015/NENAH-BIDS/blob/ccb58acb97af0c45ed4e05e9be967badc63b67a0/dMRI/registration.sh#L37) seems to cause the issue here? The default for `$meanb0` should be `meanb0_brain.mif.gz` rather than `meanb0_brain.nii.gz`?
> 
The default should be `mean_b0_brain.mif.gz`. 

> Seems what [lines 94-96](https://github.com/yukaizou2015/NENAH-BIDS/blob/ccb58acb97af0c45ed4e05e9be967badc63b67a0/dMRI/registration.sh#L94-L96) try to do is to create a `meanb0_brain.nii.gz` if there isn't one
> 
The conversion here is because FSL (FLIRT) uses .nii.gz, and not mif.gz

> In addition, a typo found for [mrcalc step line 143](https://github.com/yukaizou2015/NENAH-BIDS/blob/ccb58acb97af0c45ed4e05e9be967badc63b67a0/dMRI/registration.sh#L143), where `-mult anat/${t1w}_brain_space-dwi.mig.gz` should be `-mult anat/${t1w}_brain_space-dwi.mif.gz`
Yes, a silly typo. 

I have changed all of the above in main branch

**Comment by MarshallJordan** [comment]
I believe line 143 is still causing an issue as anat/$mask.mif.gz is used but only seems to exist as anat/$mask.nii.gz which is created on lines87-88 (where $mask is set to space-t1w_mask on line 104)

**Comment by finnlennartsson** [comment]
The script has still some instances which are not updated and sorted out. 
Will have a go now.

**Comment by finnlennartsson** [comment]
Now I have made changes in registration.sh and pulled to main branch
Try now
